### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by gustavobsch** [Lornatang/SRGAN-PyTorch#63]
Hello, the inference.py program is not working after the latest commits. Can you please fix it?

Thanks!

# python3 inference.py 
Traceback (most recent call last):
  File "inference.py", line 21, in <module>
    import imgproc
  File "/app/SRGAN-PyTorch/imgproc.py", line 513, in <module>
    center: tuple[int, int] = None,
TypeError: 'type' object is not subscriptable

**Comment by sheneman** [comment]
Same here.

**Comment by Lornatang** [comment]
Fixed

**Comment by Satyajit1993** [comment]
Still facing this error how to solve

center: tuple[int, int] = None,
TypeError: 'type' object is not subscriptable

**Comment by Lornatang** [comment]
Wait me fix this error
